[22211] Remove unbalanced "unlock cursor"
livecode/livecode-ide pull request #2092
Opened 2019-10-15 11:56 UTC by livecodepanos

This ensures `lock cursor` does not break when the pointer tool is selected

2020-04-27 13:56 UTC, runrevmark commented
I suggest updating the title of the commit message to:
```
[[ Bug 22211 ]] Remove unnecessary 'unlock cursor' in ideMouseMove
```
And then have a commit message body:
```
This patch removes a seemingly unnecessary `unlock cursor` in the IDE's
mouseMove event handler (`ideMouseMove`).

The IDE intercepts mouseMove so that it can update the resize cursor
used when the mouse is over the relevant selection handlers. It does this
by locking the cursor in this case and then changing the cursor
appropriately; unlocking the cursor when there is a selected object and
the mouse is not over a selection handle.

Previously it would also unlock the cursor if pointer tool was in effect and
there was no selected object which (because the handler is executed in
time after any user handlers) would undo any user use of `lock cursor`.
```

2020-04-27 13:56 UTC, runrevmark requested changes

2020-04-27 13:56 UTC, runrevmark commented on notes/bugfix-22211.md
> +# Ensure lock cursor does not break when the pointer tool is selected
I suggest
```
# Fix IDE interference with locking the cursor when pointer tool is selected

2020-04-27 14:36 UTC, livecodepanos commented
Setting the to WIP for further investigation, as this patch introduces this regression:

Recipe: Move from a selection handle horizontally left out of the selected objects rect.

Expected result: The cursor to switch from the resizing cursor to the usual one
Observed result: Cursor is stuck to resize cursor, even after leaving the selection handles of the selectedObject

2020-05-12 12:29 UTC, livecodepanos commented
Replaced by https://github.com/livecode/livecode-ide/pull/2132

2020-05-12 12:29 UTC, closed without merging