[[ Bug 22942 ]] Ensure the shellcommand defaults to COMSPEC on Windows
livecode/livecode-ide pull request #2145
Opened 2020-10-15 11:59 UTC by livecodepanos

2020-10-16 11:04 UTC, runrevmark requested changes

2020-10-16 11:04 UTC, runrevmark commented on Toolset/libraries/revcommonlibrary.livecodescript
>    if $COMSPEC is not empty then set the shellCommand to $COMSPEC
This can just be:
```
set the shellCommand to $COMSPEC
```
Since we are making it an error to try and `shell()` if shellCommand is empty.

2020-10-19 10:24 UTC, runrevmark approved these changes

2020-10-19 10:25 UTC, runrevmark commented
@livecode-vulcan review ok 7a3800e

2020-10-19 10:27 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 7a3800ea24bfbc14924e19eed4a650f81a441a56

2020-10-19 12:39 UTC, merged